n = int(input())
if n == 1:
    print("A")
elif n == 2:
    print("A\nBB")
elif n == 3:
    print("A\nBB\nCCC")
elif n == 4:
    print("A\nBB\nCCC\nDDDD")
elif n == 5:
    print("A\nBB\nCCC\nDDDD\nEEEEE")                  
elif n == 6:
    print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF") 
elif n == 7:
     print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG")
elif n == 8:
    print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG\nHHHHHHHH")
elif n == 9:
    print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG\nHHHHHHHH\nIIIIIIIII")
elif n == 10:
    print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG\nHHHHHHHH\nIIIIIIIII\nJJJJJJJJJJ")
elif n == 11:
    print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG\nHHHHHHHH\nIIIIIIIII\nJJJJJJJJJJ\nKKKKKKKKKKK")
elif n == 12: 
    print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG\nHHHHHHHH\nIIIIIIIII\nJJJJJJJJJJ\nKKKKKKKKKKK\nLLLLLLLLLLLL")
elif n == 13: 
    print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG\nHHHHHHHH\nIIIIIIIII\nJJJJJJJJJJ\nKKKKKKKKKKK\nLLLLLLLLLLLL\nMMMMMMMMMMMMM")
elif n == 14:                             
    print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG\nHHHHHHHH\nIIIIIIIII\nJJJJJJJJJJ\nKKKKKKKKKKK\nLLLLLLLLLLLL\nMMMMMMMMMMMMM\nNNNNNNNNNNNNNN")
elif n == 15: 
    print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG\nHHHHHHHH\nIIIIIIIII\nJJJJJJJJJJ\nKKKKKKKKKKK\nLLLLLLLLLLLL\nMMMMMMMMMMMMM\nNNNNNNNNNNNNNN\nOOOOOOOOOOOOOOO")
elif n == 16: 
    print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG\nHHHHHHHH\nIIIIIIIII\nJJJJJJJJJJ\nKKKKKKKKKKK\nLLLLLLLLLLLL\nMMMMMMMMMMMMM\nNNNNNNNNNNNNNN\nOOOOOOOOOOOOOOO\nPPPPPPPPPPPPPPPP")
elif n == 17: 
    print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG\nHHHHHHHH\nIIIIIIIII\nJJJJJJJJJJ\nKKKKKKKKKKK\nLLLLLLLLLLLL\nMMMMMMMMMMMMM\nNNNNNNNNNNNNNN\nOOOOOOOOOOOOOOO\nPPPPPPPPPPPPPPPP\nQQQQQQQQQQQQQQQQQ")
elif n == 18: 
    print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG\nHHHHHHHH\nIIIIIIIII\nJJJJJJJJJJ\nKKKKKKKKKKK\nLLLLLLLLLLLL\nMMMMMMMMMMMMM\nNNNNNNNNNNNNNN\nOOOOOOOOOOOOOOO\nPPPPPPPPPPPPPPPP\nQQQQQQQQQQQQQQQQQ\nRRRRRRRRRRRRRRRRRR")
elif n == 19: 
     print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG\nHHHHHHHH\nIIIIIIIII\nJJJJJJJJJJ\nKKKKKKKKKKK\nLLLLLLLLLLLL\nMMMMMMMMMMMMM\nNNNNNNNNNNNNNN\nOOOOOOOOOOOOOOO\nPPPPPPPPPPPPPPPP\nQQQQQQQQQQQQQQQQQ\nRRRRRRRRRRRRRRRRRR\nSSSSSSSSSSSSSSSSSSS")
elif n == 20: 
    print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG\nHHHHHHHH\nIIIIIIIII\nJJJJJJJJJJ\nKKKKKKKKKKK\nLLLLLLLLLLLL\nMMMMMMMMMMMMM\nNNNNNNNNNNNNNN\nOOOOOOOOOOOOOOO\nPPPPPPPPPPPPPPPP\nQQQQQQQQQQQQQQQQQ\nRRRRRRRRRRRRRRRRRR\nSSSSSSSSSSSSSSSSSSS\nTTTTTTTTTTTTTTTTTTTT")
elif n == 21: 
    print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG\nHHHHHHHH\nIIIIIIIII\nJJJJJJJJJJ\nKKKKKKKKKKK\nLLLLLLLLLLLL\nMMMMMMMMMMMMM\nNNNNNNNNNNNNNN\nOOOOOOOOOOOOOOO\nPPPPPPPPPPPPPPPP\nQQQQQQQQQQQQQQQQQ\nRRRRRRRRRRRRRRRRRR\nSSSSSSSSSSSSSSSSSSS\nTTTTTTTTTTTTTTTTTTTT\nUUUUUUUUUUUUUUUUUUUUU")
elif n == 22:
    print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG\nHHHHHHHH\nIIIIIIIII\nJJJJJJJJJJ\nKKKKKKKKKKK\nLLLLLLLLLLLL\nMMMMMMMMMMMMM\nNNNNNNNNNNNNNN\nOOOOOOOOOOOOOOO\nPPPPPPPPPPPPPPPP\nQQQQQQQQQQQQQQQQQ\nRRRRRRRRRRRRRRRRRR\nSSSSSSSSSSSSSSSSSSS\nTTTTTTTTTTTTTTTTTTTT\nUUUUUUUUUUUUUUUUUUUUU\nVVVVVVVVVVVVVVVVVVVVVV") 
elif n == 23: 
    print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG\nHHHHHHHH\nIIIIIIIII\nJJJJJJJJJJ\nKKKKKKKKKKK\nLLLLLLLLLLLL\nMMMMMMMMMMMMM\nNNNNNNNNNNNNNN\nOOOOOOOOOOOOOOO\nPPPPPPPPPPPPPPPP\nQQQQQQQQQQQQQQQQQ\nRRRRRRRRRRRRRRRRRR\nSSSSSSSSSSSSSSSSSSS\nTTTTTTTTTTTTTTTTTTTT\nUUUUUUUUUUUUUUUUUUUUU\nVVVVVVVVVVVVVVVVVVVVVV\nWWWWWWWWWWWWWWWWWWWWWWW")
elif n == 24: 
    print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG\nHHHHHHHH\nIIIIIIIII\nJJJJJJJJJJ\nKKKKKKKKKKK\nLLLLLLLLLLLL\nMMMMMMMMMMMMM\nNNNNNNNNNNNNNN\nOOOOOOOOOOOOOOO\nPPPPPPPPPPPPPPPP\nQQQQQQQQQQQQQQQQQ\nRRRRRRRRRRRRRRRRRR\nSSSSSSSSSSSSSSSSSSS\nTTTTTTTTTTTTTTTTTTTT\nUUUUUUUUUUUUUUUUUUUUU\nVVVVVVVVVVVVVVVVVVVVVV\nWWWWWWWWWWWWWWWWWWWWWWW\nXXXXXXXXXXXXXXXXXXXXXXXX")
elif n == 25: 
    print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG\nHHHHHHHH\nIIIIIIIII\nJJJJJJJJJJ\nKKKKKKKKKKK\nLLLLLLLLLLLL\nMMMMMMMMMMMMM\nNNNNNNNNNNNNNN\nOOOOOOOOOOOOOOO\nPPPPPPPPPPPPPPPP\nQQQQQQQQQQQQQQQQQ\nRRRRRRRRRRRRRRRRRR\nSSSSSSSSSSSSSSSSSSS\nTTTTTTTTTTTTTTTTTTTT\nUUUUUUUUUUUUUUUUUUUUU\nVVVVVVVVVVVVVVVVVVVVVV\nWWWWWWWWWWWWWWWWWWWWWWW\nXXXXXXXXXXXXXXXXXXXXXXXX\nYYYYYYYYYYYYYYYYYYYYYYYYY")
elif n == 26: 
    print("A\nBB\nCCC\nDDDD\nEEEEE\nFFFFFF\nGGGGGGG\nHHHHHHHH\nIIIIIIIII\nJJJJJJJJJJ\nKKKKKKKKKKK\nLLLLLLLLLLLL\nMMMMMMMMMMMMM\nNNNNNNNNNNNNNN\nOOOOOOOOOOOOOOO\nPPPPPPPPPPPPPPPP\nQQQQQQQQQQQQQQQQQ\nRRRRRRRRRRRRRRRRRR\nSSSSSSSSSSSSSSSSSSS\nTTTTTTTTTTTTTTTTTTTT\nUUUUUUUUUUUUUUUUUUUUU\nVVVVVVVVVVVVVVVVVVVVVV\nWWWWWWWWWWWWWWWWWWWWWWW\nXXXXXXXXXXXXXXXXXXXXXXXX\nYYYYYYYYYYYYYYYYYYYYYYYYY\nZZZZZZZZZZZZZZZZZZZZZZZZZZ") 
                                   